import fs from 'node:fs';
import path from 'node:path';

import { cli, setupUncaughtExceptionHandler } from './cli';

setupUncaughtExceptionHandler();

/**
 * Programmatic entry point for data-package bin shims generated by `filedist init`.
 *
 * Builds a synthetic single-set config from CLI args pointing to this data package.
 * Selectors (--files, --presets, etc.) are applied from the CLI args; omitting them
 * extracts all files. The data package's own filedist config in package.json is never
 * used as the CLI config here.
 *
 * @param binDir - The bin/ directory of the data package (__dirname from the shim).
 * @param args   - CLI arguments (without node + script, i.e. process.argv.slice(2)).
 */
export async function binpkg(binDir: string, args: string[]): Promise<void> {
  if (args.includes('--packages')) {
    // eslint-disable-next-line no-console
    console.log('Cannot use --packages when invoked from a data package bin shim');
    // eslint-disable-next-line unicorn/no-process-exit
    process.exit(1);
  }

  const pkgRootDir = path.join(binDir, '..');
  const pkgJson = JSON.parse(fs.readFileSync(path.join(pkgRootDir, 'package.json')).toString()) as {
    name: string;
    filedist?: {
      defaultPresets?: string[];
    };
  };
  const pkgName = pkgJson.name;
  const defaultPresets = pkgJson.filedist?.defaultPresets ?? [];

  const effectiveArgs = [...args];
  if (
    !effectiveArgs.includes('--presets') &&
    !effectiveArgs.includes('--all') &&
    defaultPresets.length > 0
  ) {
    effectiveArgs.push('--presets', defaultPresets.join(','));
  }

  // Inject --packages <pkgName> so cli builds a synthetic single-set entry from args.
  // No configCwd is passed, so the data package's own filedist config is not loaded.
  const exitCode = await cli(
    ['node', 'filedist', ...effectiveArgs, '--packages', pkgName],
    process.cwd(),
  );
  // eslint-disable-next-line unicorn/no-process-exit
  process.exit(exitCode);
}
