/* eslint-disable functional/no-try-statements */
/* eslint-disable no-console */
import fs from 'node:fs';
import path from 'node:path';

import { NpmdataConfig, NpmdataExtractEntry } from '../types';
import { actionExtract } from '../package/action-extract';
import { actionCheck } from '../package/action-check';
import { actionList } from '../package/action-list';
import { actionPurge } from '../package/action-purge';
import { filterEntriesByPresets } from '../utils';

import { parseArgv, buildEntriesFromArgv, applyArgvOverrides } from './argv';

/**
 * Entry point for self-installable packages generated by `init`.
 * Called from bin/npmdata.js: require('npmdata').run(__dirname, process.argv.slice(2))
 *
 * @param binDir   Absolute path to the bin/ directory of the hosting package.
 * @param argv     CLI arguments (process.argv.slice(2) from bin shim).
 */
// eslint-disable-next-line complexity
export async function run(binDir: string, argv: string[] = []): Promise<void> {
  const pkgDir = path.dirname(binDir);
  const pkgJsonPath = path.join(pkgDir, 'package.json');

  let pkgName = path.basename(pkgDir);
  let sets: NpmdataExtractEntry[] | undefined;

  try {
    const pkgJson = JSON.parse(fs.readFileSync(pkgJsonPath).toString()) as {
      name?: string;
      npmdata?: { sets?: NpmdataExtractEntry[] };
    };
    pkgName = pkgJson.name ?? pkgName;
    sets = pkgJson.npmdata?.sets;
  } catch {
    // No package.json or parse error
  }

  // Fallback: synthetic single-entry when no sets defined
  const entries: NpmdataExtractEntry[] = sets ?? [{ package: pkgName, output: { path: '.' } }];

  const config: NpmdataConfig = { sets: entries };
  const cwd = process.cwd();

  // Parse command from argv (same as CLI)
  const firstArg = argv[0];
  const KNOWN_COMMANDS = new Set(['extract', 'check', 'list', 'purge']);
  let command = 'extract';
  let cmdArgs = argv;

  if (firstArg && KNOWN_COMMANDS.has(firstArg)) {
    command = firstArg;
    cmdArgs = argv.slice(1);
  }

  let parsed;
  try {
    parsed = parseArgv(cmdArgs);
  } catch (error: unknown) {
    console.error(`Error: ${(error as Error).message}`);
    process.exitCode = 1;
    return;
  }

  // --packages overrides sets
  const cliEntries = buildEntriesFromArgv(parsed);
  const activeEntries = cliEntries ?? entries;
  const overridden = applyArgvOverrides(activeEntries, parsed);
  const presets = parsed.presets ?? [];
  const filtered = filterEntriesByPresets(overridden, presets);

  try {
    switch (command) {
      case 'extract': {
        await actionExtract({ entries: filtered, config, cwd });
        break;
      }
      case 'check': {
        const summary = await actionCheck({ entries: filtered, config, cwd });
        if (summary.missing.length > 0 || summary.modified.length > 0 || summary.extra.length > 0) {
          for (const f of summary.missing) console.log(`missing: ${f}`);
          for (const f of summary.modified) console.log(`modified: ${f}`);
          for (const f of summary.extra) console.log(`extra: ${f}`);
          process.exitCode = 1;
        }
        break;
      }
      case 'list': {
        const files = await actionList({ entries: filtered, config, cwd });
        for (const f of files) {
          console.log(`${f.path}  ${f.packageName}@${f.packageVersion}`);
        }
        break;
      }
      case 'purge': {
        await actionPurge({ entries: filtered, config, cwd, presets, dryRun: parsed.dryRun });
        break;
      }
      default:
        console.error(`Unknown command: ${command}`);
        process.exitCode = 1;
    }
  } catch (error: unknown) {
    console.error(`Error: ${(error as Error).message}`);
    process.exitCode = 1;
  }
}
