#!/usr/bin/env node
/* eslint-disable promise/prefer-await-to-callbacks */
import { cli } from './cli/cli';

/**
 * Programmatic entry point for consumer packages.
 * Called by the bin shim generated by `npmdata init`.
 *
 * @param cwd  - Working directory of the consumer package.
 * @param args - CLI arguments (without node + script, i.e. process.argv.slice(2)).
 */
export async function main(cwd: string, args: string[]): Promise<void> {
  await cli(['node', 'npmdata', ...args], cwd);
}

main(process.cwd(), process.argv.slice(2)).catch((error: unknown) => {
  // eslint-disable-next-line no-console
  console.error((error as Error).message);
  process.exitCode = 1;
});
